package movies;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Joao Pereira' at '12/6/16 1:32 PM' with Gradle 3.0
 *
 * @author Joao Pereira, @date 12/6/16 1:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
