import org.junit.Test;

import movies.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Joao Pereira' at '12/6/16 1:32 PM' with Gradle 3.0
 *
 * @author Joao Pereira, @date 12/6/16 1:32 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
